[package]
name = "whimsi-table-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.101"
darling = "0.21.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
